// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodels

type Article struct {
	ID        string  `json:"id"`
	Title     *string `json:"title"`
	CreateAt  *int    `json:"createAt"`
	UpdatedAt *int    `json:"updatedAt"`
	DeletedAt *int    `json:"deletedAt"`
}

type Author struct {
	ID        string     `json:"id"`
	FirstName *string    `json:"firstName"`
	LastName  *string    `json:"lastName"`
	Username  *string    `json:"username"`
	Password  *string    `json:"password"`
	Active    *bool      `json:"active"`
	Articles  []*Article `json:"articles"`
	CreateAt  *int       `json:"createAt"`
	UpdatedAt *int       `json:"updatedAt"`
	DeletedAt *int       `json:"deletedAt"`
}
