// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Articles       string
	Authors        string
	GorpMigrations string
}{
	Articles:       "articles",
	Authors:        "authors",
	GorpMigrations: "gorp_migrations",
}
