// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CaseStatus                string
	Employees                 string
	GorpMigrations            string
	IncidentReportAttachments string
	IncidentReports           string
	Notices                   string
	Roles                     string
	Users                     string
}{
	CaseStatus:                "case_status",
	Employees:                 "employees",
	GorpMigrations:            "gorp_migrations",
	IncidentReportAttachments: "incident_report_attachments",
	IncidentReports:           "incident_reports",
	Notices:                   "notices",
	Roles:                     "roles",
	Users:                     "users",
}
