// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// IncidentReportAttachment is an object representing the database table.
type IncidentReportAttachment struct {
	ID               int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	IncidentReportID int         `boil:"incident_report_id" json:"incident_report_id" toml:"incident_report_id" yaml:"incident_report_id"`
	URL              null.String `boil:"url" json:"url,omitempty" toml:"url" yaml:"url,omitempty"`
	CreatedAt        time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt        null.Time   `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	DeletedAt        null.Time   `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *incidentReportAttachmentR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L incidentReportAttachmentL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var IncidentReportAttachmentColumns = struct {
	ID               string
	IncidentReportID string
	URL              string
	CreatedAt        string
	UpdatedAt        string
	DeletedAt        string
}{
	ID:               "id",
	IncidentReportID: "incident_report_id",
	URL:              "url",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
	DeletedAt:        "deleted_at",
}

var IncidentReportAttachmentTableColumns = struct {
	ID               string
	IncidentReportID string
	URL              string
	CreatedAt        string
	UpdatedAt        string
	DeletedAt        string
}{
	ID:               "incident_report_attachments.id",
	IncidentReportID: "incident_report_attachments.incident_report_id",
	URL:              "incident_report_attachments.url",
	CreatedAt:        "incident_report_attachments.created_at",
	UpdatedAt:        "incident_report_attachments.updated_at",
	DeletedAt:        "incident_report_attachments.deleted_at",
}

// Generated where

var IncidentReportAttachmentWhere = struct {
	ID               whereHelperint
	IncidentReportID whereHelperint
	URL              whereHelpernull_String
	CreatedAt        whereHelpertime_Time
	UpdatedAt        whereHelpernull_Time
	DeletedAt        whereHelpernull_Time
}{
	ID:               whereHelperint{field: "`incident_report_attachments`.`id`"},
	IncidentReportID: whereHelperint{field: "`incident_report_attachments`.`incident_report_id`"},
	URL:              whereHelpernull_String{field: "`incident_report_attachments`.`url`"},
	CreatedAt:        whereHelpertime_Time{field: "`incident_report_attachments`.`created_at`"},
	UpdatedAt:        whereHelpernull_Time{field: "`incident_report_attachments`.`updated_at`"},
	DeletedAt:        whereHelpernull_Time{field: "`incident_report_attachments`.`deleted_at`"},
}

// IncidentReportAttachmentRels is where relationship names are stored.
var IncidentReportAttachmentRels = struct {
	IncidentReport string
}{
	IncidentReport: "IncidentReport",
}

// incidentReportAttachmentR is where relationships are stored.
type incidentReportAttachmentR struct {
	IncidentReport *IncidentReport `boil:"IncidentReport" json:"IncidentReport" toml:"IncidentReport" yaml:"IncidentReport"`
}

// NewStruct creates a new relationship struct
func (*incidentReportAttachmentR) NewStruct() *incidentReportAttachmentR {
	return &incidentReportAttachmentR{}
}

func (r *incidentReportAttachmentR) GetIncidentReport() *IncidentReport {
	if r == nil {
		return nil
	}
	return r.IncidentReport
}

// incidentReportAttachmentL is where Load methods for each relationship are stored.
type incidentReportAttachmentL struct{}

var (
	incidentReportAttachmentAllColumns            = []string{"id", "incident_report_id", "url", "created_at", "updated_at", "deleted_at"}
	incidentReportAttachmentColumnsWithoutDefault = []string{"incident_report_id", "url", "updated_at", "deleted_at"}
	incidentReportAttachmentColumnsWithDefault    = []string{"id", "created_at"}
	incidentReportAttachmentPrimaryKeyColumns     = []string{"id"}
	incidentReportAttachmentGeneratedColumns      = []string{}
)

type (
	// IncidentReportAttachmentSlice is an alias for a slice of pointers to IncidentReportAttachment.
	// This should almost always be used instead of []IncidentReportAttachment.
	IncidentReportAttachmentSlice []*IncidentReportAttachment

	incidentReportAttachmentQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	incidentReportAttachmentType                 = reflect.TypeOf(&IncidentReportAttachment{})
	incidentReportAttachmentMapping              = queries.MakeStructMapping(incidentReportAttachmentType)
	incidentReportAttachmentPrimaryKeyMapping, _ = queries.BindMapping(incidentReportAttachmentType, incidentReportAttachmentMapping, incidentReportAttachmentPrimaryKeyColumns)
	incidentReportAttachmentInsertCacheMut       sync.RWMutex
	incidentReportAttachmentInsertCache          = make(map[string]insertCache)
	incidentReportAttachmentUpdateCacheMut       sync.RWMutex
	incidentReportAttachmentUpdateCache          = make(map[string]updateCache)
	incidentReportAttachmentUpsertCacheMut       sync.RWMutex
	incidentReportAttachmentUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single incidentReportAttachment record from the query.
func (q incidentReportAttachmentQuery) One(ctx context.Context, exec boil.ContextExecutor) (*IncidentReportAttachment, error) {
	o := &IncidentReportAttachment{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for incident_report_attachments")
	}

	return o, nil
}

// All returns all IncidentReportAttachment records from the query.
func (q incidentReportAttachmentQuery) All(ctx context.Context, exec boil.ContextExecutor) (IncidentReportAttachmentSlice, error) {
	var o []*IncidentReportAttachment

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to IncidentReportAttachment slice")
	}

	return o, nil
}

// Count returns the count of all IncidentReportAttachment records in the query.
func (q incidentReportAttachmentQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count incident_report_attachments rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q incidentReportAttachmentQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if incident_report_attachments exists")
	}

	return count > 0, nil
}

// IncidentReport pointed to by the foreign key.
func (o *IncidentReportAttachment) IncidentReport(mods ...qm.QueryMod) incidentReportQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.IncidentReportID),
	}

	queryMods = append(queryMods, mods...)

	return IncidentReports(queryMods...)
}

// LoadIncidentReport allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (incidentReportAttachmentL) LoadIncidentReport(ctx context.Context, e boil.ContextExecutor, singular bool, maybeIncidentReportAttachment interface{}, mods queries.Applicator) error {
	var slice []*IncidentReportAttachment
	var object *IncidentReportAttachment

	if singular {
		object = maybeIncidentReportAttachment.(*IncidentReportAttachment)
	} else {
		slice = *maybeIncidentReportAttachment.(*[]*IncidentReportAttachment)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &incidentReportAttachmentR{}
		}
		args = append(args, object.IncidentReportID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &incidentReportAttachmentR{}
			}

			for _, a := range args {
				if a == obj.IncidentReportID {
					continue Outer
				}
			}

			args = append(args, obj.IncidentReportID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`incident_reports`),
		qm.WhereIn(`incident_reports.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load IncidentReport")
	}

	var resultSlice []*IncidentReport
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice IncidentReport")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for incident_reports")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for incident_reports")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.IncidentReport = foreign
		if foreign.R == nil {
			foreign.R = &incidentReportR{}
		}
		foreign.R.IncidentReportAttachments = append(foreign.R.IncidentReportAttachments, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.IncidentReportID == foreign.ID {
				local.R.IncidentReport = foreign
				if foreign.R == nil {
					foreign.R = &incidentReportR{}
				}
				foreign.R.IncidentReportAttachments = append(foreign.R.IncidentReportAttachments, local)
				break
			}
		}
	}

	return nil
}

// SetIncidentReport of the incidentReportAttachment to the related item.
// Sets o.R.IncidentReport to related.
// Adds o to related.R.IncidentReportAttachments.
func (o *IncidentReportAttachment) SetIncidentReport(ctx context.Context, exec boil.ContextExecutor, insert bool, related *IncidentReport) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `incident_report_attachments` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"incident_report_id"}),
		strmangle.WhereClause("`", "`", 0, incidentReportAttachmentPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.IncidentReportID = related.ID
	if o.R == nil {
		o.R = &incidentReportAttachmentR{
			IncidentReport: related,
		}
	} else {
		o.R.IncidentReport = related
	}

	if related.R == nil {
		related.R = &incidentReportR{
			IncidentReportAttachments: IncidentReportAttachmentSlice{o},
		}
	} else {
		related.R.IncidentReportAttachments = append(related.R.IncidentReportAttachments, o)
	}

	return nil
}

// IncidentReportAttachments retrieves all the records using an executor.
func IncidentReportAttachments(mods ...qm.QueryMod) incidentReportAttachmentQuery {
	mods = append(mods, qm.From("`incident_report_attachments`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`incident_report_attachments`.*"})
	}

	return incidentReportAttachmentQuery{q}
}

// FindIncidentReportAttachment retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindIncidentReportAttachment(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*IncidentReportAttachment, error) {
	incidentReportAttachmentObj := &IncidentReportAttachment{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `incident_report_attachments` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, incidentReportAttachmentObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from incident_report_attachments")
	}

	return incidentReportAttachmentObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *IncidentReportAttachment) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no incident_report_attachments provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(incidentReportAttachmentColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	incidentReportAttachmentInsertCacheMut.RLock()
	cache, cached := incidentReportAttachmentInsertCache[key]
	incidentReportAttachmentInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			incidentReportAttachmentAllColumns,
			incidentReportAttachmentColumnsWithDefault,
			incidentReportAttachmentColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(incidentReportAttachmentType, incidentReportAttachmentMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(incidentReportAttachmentType, incidentReportAttachmentMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `incident_report_attachments` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `incident_report_attachments` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `incident_report_attachments` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, incidentReportAttachmentPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into incident_report_attachments")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == incidentReportAttachmentMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for incident_report_attachments")
	}

CacheNoHooks:
	if !cached {
		incidentReportAttachmentInsertCacheMut.Lock()
		incidentReportAttachmentInsertCache[key] = cache
		incidentReportAttachmentInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the IncidentReportAttachment.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *IncidentReportAttachment) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	key := makeCacheKey(columns, nil)
	incidentReportAttachmentUpdateCacheMut.RLock()
	cache, cached := incidentReportAttachmentUpdateCache[key]
	incidentReportAttachmentUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			incidentReportAttachmentAllColumns,
			incidentReportAttachmentPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update incident_report_attachments, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `incident_report_attachments` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, incidentReportAttachmentPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(incidentReportAttachmentType, incidentReportAttachmentMapping, append(wl, incidentReportAttachmentPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update incident_report_attachments row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for incident_report_attachments")
	}

	if !cached {
		incidentReportAttachmentUpdateCacheMut.Lock()
		incidentReportAttachmentUpdateCache[key] = cache
		incidentReportAttachmentUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q incidentReportAttachmentQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for incident_report_attachments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for incident_report_attachments")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o IncidentReportAttachmentSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), incidentReportAttachmentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `incident_report_attachments` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, incidentReportAttachmentPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in incidentReportAttachment slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all incidentReportAttachment")
	}
	return rowsAff, nil
}

var mySQLIncidentReportAttachmentUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *IncidentReportAttachment) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no incident_report_attachments provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	nzDefaults := queries.NonZeroDefaultSet(incidentReportAttachmentColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLIncidentReportAttachmentUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	incidentReportAttachmentUpsertCacheMut.RLock()
	cache, cached := incidentReportAttachmentUpsertCache[key]
	incidentReportAttachmentUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			incidentReportAttachmentAllColumns,
			incidentReportAttachmentColumnsWithDefault,
			incidentReportAttachmentColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			incidentReportAttachmentAllColumns,
			incidentReportAttachmentPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert incident_report_attachments, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`incident_report_attachments`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `incident_report_attachments` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(incidentReportAttachmentType, incidentReportAttachmentMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(incidentReportAttachmentType, incidentReportAttachmentMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for incident_report_attachments")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == incidentReportAttachmentMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(incidentReportAttachmentType, incidentReportAttachmentMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for incident_report_attachments")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for incident_report_attachments")
	}

CacheNoHooks:
	if !cached {
		incidentReportAttachmentUpsertCacheMut.Lock()
		incidentReportAttachmentUpsertCache[key] = cache
		incidentReportAttachmentUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single IncidentReportAttachment record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *IncidentReportAttachment) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no IncidentReportAttachment provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), incidentReportAttachmentPrimaryKeyMapping)
	sql := "DELETE FROM `incident_report_attachments` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from incident_report_attachments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for incident_report_attachments")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q incidentReportAttachmentQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no incidentReportAttachmentQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from incident_report_attachments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for incident_report_attachments")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o IncidentReportAttachmentSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), incidentReportAttachmentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `incident_report_attachments` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, incidentReportAttachmentPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from incidentReportAttachment slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for incident_report_attachments")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *IncidentReportAttachment) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindIncidentReportAttachment(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *IncidentReportAttachmentSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := IncidentReportAttachmentSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), incidentReportAttachmentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `incident_report_attachments`.* FROM `incident_report_attachments` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, incidentReportAttachmentPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in IncidentReportAttachmentSlice")
	}

	*o = slice

	return nil
}

// IncidentReportAttachmentExists checks if the IncidentReportAttachment row exists.
func IncidentReportAttachmentExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `incident_report_attachments` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if incident_report_attachments exists")
	}

	return exists, nil
}
