// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Articles", testArticlesUpsert)

	t.Run("Authors", testAuthorsUpsert)

	t.Run("GorpMigrations", testGorpMigrationsUpsert)
}
